### ISSUE TITLE
Issue in About Section

### ISSUE THREAD

**Issue by aikanshboyal** [data-charya/Elemental#11] opened 2022-03-02 14:45 UTC
**Describe the bug**
I noticed a safe area issue in the about section which makes it less attractive while scrolling. 

**To Reproduce**
1. Run the app on VSCode or any other IDE of your choice. View the app through your emulator or mobile device(I viewed it on a Google Pixel 4 Emulator)
2. Navigate to the 4th page(About Section) in the bottom navigation bar to view the issue. 

**Expected behavior**
The text widget 'About the Dev' shouldn't be seen in the safe area while scrolling as compared to other sections. 

**Screenshots**

![about_issue](https://user-images.githubusercontent.com/75120140/156383271-9a81cf0f-0ba4-42d4-b3ba-ae9ecbd52b6e.png)

If possible, I would love to work on this issue and solve it as soon as possible

**Comment by data-charya** [comment] 2022-03-02 15:12
Sure please do go ahead. I'm assigning this issue to you.

**Comment by Harryalways317** [comment] 2022-03-04 08:06
Hey if the issue is still open i want to work on this

**Comment by data-charya** [comment] 2022-03-04 08:08
@Harryalways317 I think @aikanshboyal is currently working on it

**Closed** 2022-03-07 03:10 UTC
Labels: GSSoC22, Level1
